// Automatically generated by makemoduledefs.py.

#if (1)
    extern const struct _mp_obj_module_t mp_module_bma423;
    #define MODULE_DEF_MP_QSTR_BMA423 { MP_ROM_QSTR(MP_QSTR_bma423), MP_ROM_PTR(&mp_module_bma423) },
#else
    #define MODULE_DEF_MP_QSTR_BMA423
#endif

#if (1)
    extern const struct _mp_obj_module_t mp_module_ft6x36;
    #define MODULE_DEF_MP_QSTR_FT6X36 { MP_ROM_QSTR(MP_QSTR_ft6x36), MP_ROM_PTR(&mp_module_ft6x36) },
#else
    #define MODULE_DEF_MP_QSTR_FT6X36
#endif

#if (1)
    extern const struct _mp_obj_module_t mp_module_ir;
    #define MODULE_DEF_MP_QSTR_IR { MP_ROM_QSTR(MP_QSTR_ir), MP_ROM_PTR(&mp_module_ir) },
#else
    #define MODULE_DEF_MP_QSTR_IR
#endif

#if (1)
    extern const struct _mp_obj_module_t mp_module_st7789_lvgl;
    #define MODULE_DEF_MP_QSTR_ST7789_LVGL { MP_ROM_QSTR(MP_QSTR_st7789_lvgl), MP_ROM_PTR(&mp_module_st7789_lvgl) },
#else
    #define MODULE_DEF_MP_QSTR_ST7789_LVGL
#endif

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_uarray;
    #define MODULE_DEF_MP_QSTR_UARRAY { MP_ROM_QSTR(MP_QSTR_uarray), MP_ROM_PTR(&mp_module_uarray) },
#else
    #define MODULE_DEF_MP_QSTR_UARRAY
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_BMA423 \
    MODULE_DEF_MP_QSTR_FT6X36 \
    MODULE_DEF_MP_QSTR_IR \
    MODULE_DEF_MP_QSTR_ST7789_LVGL \
    MODULE_DEF_MP_QSTR_UARRAY \
// MICROPY_REGISTERED_MODULES
