#pragma once
#define CONFIG_LVGL_TOUCH_CONTROLLER 2
#define CONFIG_LVGL_TOUCH_CONTROLLER_FT6X06 1
#define CONFIG_LVGL_TOUCH_DRIVER_PROTOCOL_I2C 1
#define CONFIG_LVGL_TOUCH_I2C_PORT_0 1
#define CONFIG_LVGL_TOUCH_I2C_SDA 23
#define CONFIG_LVGL_TOUCH_I2C_SCL 32