/*
* Config file for display driver on ST7789V controller
 */
#pragma once
#define CONFIG_LVGL_ENABLE_TOUCH 0
#define CONFIG_LVGL_PREDEFINED_DISPLAY_NONE 1
#define CONFIG_LVGL_TFT_DISPLAY_CONTROLLER_ST7789 1
#define CONFIG_LVGL_TFT_DISPLAY_PROTOCOL_SPI 1
#define CONFIG_LVGL_PREDEFINED_PINS_NONE 1
#define CONFIG_LVGL_TFT_DISPLAY_USER_CONTROLLER_ST7789 1
#define CONFIG_LVGL_TFT_DISPLAY_SPI_HSPI 1
#define CONFIG_LVGL_DISPLAY_ORIENTATION_LANDSCAPE_INVERTED 1
#define CONFIG_LVGL_DISPLAY_ORIENTATION 3
#define CONFIG_LVGL_DISPLAY_WIDTH 240
#define CONFIG_LVGL_DISPLAY_HEIGHT 240
#define CONFIG_LVGL_TFT_CUSTOM_SPI_CLK_DIVIDER 2
#define CONFIG_LVGL_AXP192_PIN_SDA 21
#define CONFIG_LVGL_AXP192_PIN_SCL 22
#define CONFIG_LVGL_DISP_SPI_MOSI 19
#define CONFIG_LVGL_DISP_SPI_CLK 18
#define CONFIG_LVGL_DISPLAY_USE_SPI_CS 1
#define CONFIG_LVGL_DISP_SPI_CS 5
#define CONFIG_LVGL_DISPLAY_USE_DC 1
#define CONFIG_LVGL_DISP_PIN_DC 27
#define CONFIG_LVGL_DISP_PIN_RST 0
#define CONFIG_LVGL_DISP_PIN_BUSY 35
#define CONFIG_LVGL_ENABLE_BACKLIGHT_CONTROL 1
#define CONFIG_LVGL_BACKLIGHT_ACTIVE_LVL 1
#define CONFIG_LVGL_DISP_PIN_BCKL 12
#define CONFIG_LVGL_DISP_PIN_SDA 5
#define CONFIG_LVGL_DISP_PIN_SCL 4